### ISSUE TITLE
bug: pg-differ CLI has issues on Macos

### ISSUE THREAD

**Issue by thefliik** [av-dev/postgres-differ#49]
While attempting to test the `pg-differ` cli on Macos, I ran into a `env: node\r: No such file or directory` error.

I was able to resolve the issue by following the instructions in [this S.O. answer](https://stackoverflow.com/a/31041038/5490505). The problem is apparently caused because the `pg-differ` CLI source code file has windows style line endings.

**Comment by av-dev** [comment]
Hi,
Thanks for the good description
I will solve this problem as soon as possible and try to configure the project to avoid this problem in the future

**Comment by av-dev** [comment]
@thefliik This bug is fixed in [v2.2.1](https://github.com/av-dev/postgres-differ/blob/master/CHANGELOG.md#221)

**Comment by thefliik** [comment]
Awesome! 👍
